export interface UpgradeNode {
    id: string
    desc: string
    icon: string
    cost: { currency: 'gem' | 'green_core' | 'purple_core' | 'yellow_core', amount: number }[]
    parents: string[]
    x: number
    y: number
}

export const UPGRADE_NODES: UpgradeNode[] = [
    {
        id: 'drill_dmg_1',
        desc: '+1% drill damage.',
        icon: 'drill-DMG.svg',
        cost: [{ currency: 'gem', amount: 30 }],
        parents: [],
        x: 200,
        y: 300,
    },
    {
        id: 'drill_dmg_2',
        desc: '+2% drill damage.',
        icon: 'drill-DMG.svg',
        cost: [{ currency: 'gem', amount: 120 }],
        parents: ['drill_dmg_1'],
        x: 420,
        y: 360,
    },
    {
        id: 'drill_dmg_3',
        desc: '+3% drill damage.',
        icon: 'drill-DMG.svg',
        cost: [{ currency: 'gem', amount: 450 }],
        parents: ['drill_dmg_2'],
        x: 640,
        y: 420,
    },
    {
        id: 'drill_dmg_4',
        desc: '+4% drill damage.',
        icon: 'drill-DMG.svg',
        cost: [{ currency: 'gem', amount: 1080 }],
        parents: ['drill_dmg_3'],
        x: 860,
        y: 480,
    },
    {
        id: 'drill_dmg_5',
        desc: '+5% drill damage.',
        icon: 'drill-DMG.svg',
        cost: [{ currency: 'gem', amount: 1600 }],
        parents: ['drill_dmg_4'],
        x: 1080,
        y: 540,
    },
    {
        id: 'hp_1',
        desc: '+1% hp.',
        icon: 'gem.svg',
        cost: [{ currency: 'gem', amount: 30 }],
        parents: [],
        x: 1600,
        y: 300,
    },
    {
        id: 'hp_2',
        desc: '+2% hp.',
        icon: 'gem.svg',
        cost: [{ currency: 'gem', amount: 120 }],
        parents: ['hp_1'],
        x: 1820,
        y: 360,
    },
    {
        id: 'hp_3',
        desc: '+3% hp.',
        icon: 'gem.svg',
        cost: [{ currency: 'gem', amount: 450 }],
        parents: ['hp_2'],
        x: 2040,
        y: 420,
    },
    {
        id: 'hp_4',
        desc: '+4% hp.',
        icon: 'gem.svg',
        cost: [{ currency: 'gem', amount: 1080 }],
        parents: ['hp_3'],
        x: 2260,
        y: 480,
    },
    {
        id: 'hp_5',
        desc: '+5% hp.',
        icon: 'gem.svg',
        cost: [{ currency: 'gem', amount: 1600 }],
        parents: ['hp_4'],
        x: 2480,
        y: 540,
    },
    {
        id: 'drill_length_1',
        desc: '+1% drill length.',
        icon: 'drill-length.svg',
        cost: [{ currency: 'gem', amount: 30 }],
        parents: [],
        x: 200,
        y: 600,
    },
    {
        id: 'drill_length_2',
        desc: '+2% drill length.',
        icon: 'drill-length.svg',
        cost: [{ currency: 'gem', amount: 120 }],
        parents: ['drill_length_1'],
        x: 420,
        y: 660,
    },
    {
        id: 'drill_length_3',
        desc: '+3% drill length.',
        icon: 'drill-length.svg',
        cost: [{ currency: 'gem', amount: 450 }],
        parents: ['drill_length_2'],
        x: 640,
        y: 720,
    },
    {
        id: 'drill_length_4',
        desc: '+4% drill length.',
        icon: 'drill-length.svg',
        cost: [{ currency: 'gem', amount: 1080 }],
        parents: ['drill_length_3'],
        x: 860,
        y: 780,
    },
    {
        id: 'drill_length_5',
        desc: '+5% drill length.',
        icon: 'drill-length.svg',
        cost: [{ currency: 'gem', amount: 1600 }],
        parents: ['drill_length_4'],
        x: 1080,
        y: 840,
    },
    {
        id: 'movement_1',
        desc: '+1% MOVEMENT.',
        icon: 'gem.svg',
        cost: [{ currency: 'gem', amount: 30 }],
        parents: [],
        x: 1600,
        y: 600,
    },
    {
        id: 'movement_2',
        desc: '+2% MOVEMENT.',
        icon: 'gem.svg',
        cost: [{ currency: 'gem', amount: 120 }],
        parents: ['movement_1'],
        x: 1820,
        y: 660,
    },
    {
        id: 'movement_3',
        desc: '+3% MOVEMENT.',
        icon: 'gem.svg',
        cost: [{ currency: 'gem', amount: 450 }],
        parents: ['movement_2'],
        x: 2040,
        y: 720,
    },
    {
        id: 'movement_4',
        desc: '+4% MOVEMENT.',
        icon: 'gem.svg',
        cost: [{ currency: 'gem', amount: 1080 }],
        parents: ['movement_3'],
        x: 2260,
        y: 780,
    },
    {
        id: 'movement_5',
        desc: '+5% MOVEMENT.',
        icon: 'gem.svg',
        cost: [{ currency: 'gem', amount: 1600 }],
        parents: ['movement_4'],
        x: 2480,
        y: 840,
    },
]