export interface UpgradeNode {
    id: string
    desc: string
    cost: { currency: 'gem' | 'green_core' | 'purple_core' | 'yellow_core', amount: number }[]
    parents: string[]
    x: number
    y: number
}

export const UPGRADE_NODES: UpgradeNode[] = [
    {
        id: 'drill_dmg_1',
        desc: '+1% drill damage',
        cost: [{ currency: 'gem', amount: 30 }],
        parents: [],
        x: 200,
        y: 300,
    },
    {
        id: 'drill_dmg_2',
        desc: '+2% drill damage',
        cost: [{ currency: 'gem', amount: 120 }],
        parents: ['drill_dmg_1'],
        x: 420,
        y: 360,
    },
    {
        id: 'drill_dmg_3',
        desc: '+3% drill damage',
        cost: [{ currency: 'gem', amount: 450 }],
        parents: ['drill_dmg_2'],
        x: 640,
        y: 420,
    },
    {
        id: 'drill_dmg_4',
        desc: '+4% drill damage',
        cost: [{ currency: 'gem', amount: 1080 }],
        parents: ['drill_dmg_3'],
        x: 860,
        y: 480,
    },
    {
        id: 'drill_dmg_5',
        desc: '+5% drill damage',
        cost: [{ currency: 'gem', amount: 1600 }],
        parents: ['drill_dmg_4'],
        x: 1080,
        y: 540,
    },
    {
        id: 'HP_1',
        desc: '+1% HP',
        cost: [{ currency: 'gem', amount: 30 }],
        parents: [],
        x: 1600,
        y: 300,
    },
    {
        id: 'HP_2',
        desc: '+2% HP',
        cost: [{ currency: 'gem', amount: 120 }],
        parents: ['HP_1'],
        x: 1820,
        y: 360,
    },
    {
        id: 'HP_3',
        desc: '+3% HP',
        cost: [{ currency: 'gem', amount: 450 }],
        parents: ['HP_2'],
        x: 2040,
        y: 420,
    },
    {
        id: 'HP_4',
        desc: '+4% HP',
        cost: [{ currency: 'gem', amount: 1080 }],
        parents: ['HP_3'],
        x: 2260,
        y: 480,
    },
    {
        id: 'HP_5',
        desc: '+5% HP',
        cost: [{ currency: 'gem', amount: 1600 }],
        parents: ['HP_4'],
        x: 2480,
        y: 540,
    },
    {
        id: 'drill_length_1',
        desc: '+1% drill length',
        cost: [{ currency: 'gem', amount: 30 }],
        parents: [],
        x: 200,
        y: 600,
    },
    {
        id: 'drill_length_2',
        desc: '+2% drill length',
        cost: [{ currency: 'gem', amount: 120 }],
        parents: ['drill_length_1'],
        x: 420,
        y: 660,
    },
    {
        id: 'drill_length_3',
        desc: '+3% drill length',
        cost: [{ currency: 'gem', amount: 450 }],
        parents: ['drill_length_2'],
        x: 640,
        y: 720,
    },
    {
        id: 'drill_length_4',
        desc: '+4% drill length',
        cost: [{ currency: 'gem', amount: 1080 }],
        parents: ['drill_length_3'],
        x: 860,
        y: 780,
    },
    {
        id: 'drill_length_5',
        desc: '+5% drill length',
        cost: [{ currency: 'gem', amount: 1600 }],
        parents: ['drill_length_4'],
        x: 1080,
        y: 840,
    },
    {
        id: 'movement_1',
        desc: '+1% movement',
        cost: [{ currency: 'gem', amount: 30 }],
        parents: [],
        x: 1600,
        y: 600,
    },
    {
        id: 'movement_2',
        desc: '+2% movement',
        cost: [{ currency: 'gem', amount: 120 }],
        parents: ['movement_1'],
        x: 1820,
        y: 660,
    },
    {
        id: 'movement_3',
        desc: '+3% movement',
        cost: [{ currency: 'gem', amount: 450 }],
        parents: ['movement_2'],
        x: 2040,
        y: 720,
    },
    {
        id: 'movement_4',
        desc: '+4% movement',
        cost: [{ currency: 'gem', amount: 1080 }],
        parents: ['movement_3'],
        x: 2260,
        y: 780,
    },
    {
        id: 'movement_5',
        desc: '+5% movement',
        cost: [{ currency: 'gem', amount: 1600 }],
        parents: ['movement_4'],
        x: 2480,
        y: 840,
    },
]